exclude         : [bc]
contact         : "info@software-carpentry.org"
facebook_url    : "https://www.facebook.com/SoftwareCarpentry"
github_url      : "https://github.com/swcarpentry"
google_plus_url : "https://plus.google.com/u/0/114244759874490019250/posts"
rss_url         : "http://software-carpentry.org/feed.xml"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
recent_length   : 10
blog_title      : "Software Carpentry"
blog_subtitle   : "Helping scientists make better software since 1998"
flag_size       : 16
badges : {
    "creator" : [
        {"name" : "Steve Crouch",               "user" : "crouch.s"},
        {"name" : "Richard 'Tommy' Guy",        "user" : "guy.t"},
        {"name" : "Mike Jackson",               "user" : "jackson.m"},
        {"name" : "Jason Montojo",              "user" : "montojo.j"},
        {"name" : "Jon Pipitone",               "user" : "pipitone.j"},
        {"name" : "Ethan White",                "user" : "white.e"},
        {"name" : "Greg Wilson",                "user" : "wilson.g"}
    ],
    "instructor" : [
        {"name" : "Aron Ahmadia",               "user" : "ahmadia.a"},
        {"name" : "Carlos Anderson",            "user" : "anderson.c"},
        {"name" : "Dhavide Aruliah",            "user" : "aruliah.d"},
        {"name" : "Azalee Bostroem",            "user" : "bostroem.a"},
        {"name" : "Erik Bray",                  "user" : "bray.e"},
        {"name" : "C. Titus Brown",             "user" : "brown.ct"},
        {"name" : "Jennifer Bryan",             "user" : "bryan.j"},
        {"name" : "Rosangela Canino-Koning",    "user" : "canino-koning.r"},
        {"name" : "Chris Cannam",               "user" : "cannam.c"},
        {"name" : "Shreyas Cholia",             "user" : "cholia.s"},
        {"name" : "Adina Chuang Howe",          "user" : "chuang-howe.a"},
        {"name" : "Neil Chue Hong",             "user" : "chue-hong.n"},
        {"name" : "Stefano Cozzini",            "user" : "cozzini.s"},
        {"name" : "Steve Crouch",               "user" : "crouch.s"},
        {"name" : "Matt Davis",                 "user" : "davis.m"},
        {"name" : "Ross Dickson",               "user" : "dickson.r"},
        {"name" : "Jonathan Dursi",             "user" : "dursi.j"},
        {"name" : "Justin Ely",                 "user" : "ely.j"},
        {"name" : "Richard Enbody",             "user" : "enbody.r"},
        {"name" : "Luis Figueira",              "user" : "figueira.l"},
        {"name" : "Julia Gustavsen",            "user" : "gustavsen.j"},
        {"name" : "Richard 'Tommy' Guy",        "user" : "guy.t"},
        {"name" : "Steve Haddock",              "user" : "haddock.s"},
        {"name" : "Mike Hansen",                "user" : "hansen.m"},
        {"name" : "Ted Hart",                   "user" : "hart.t"},
        {"name" : "Konrad Hinsen",              "user" : "hinsen.k"},
        {"name" : "Katy Huff",                  "user" : "huff.k"},
        {"name" : "Paul Ivanov",                "user" : "ivanov.p"},
        {"name" : "Mike Jackson",               "user" : "jackson.m"},
        {"name" : "David Jones",                "user" : "jones.d"},
        {"name" : "Jessica Kerr",               "user" : "kerr.j"},
        {"name" : "Justin Kitzes",              "user" : "kitzes.j"},
        {"name" : "Bernhard Konrad",            "user" : "konrad.b"},
        {"name" : "Karin Lagesen",              "user" : "lagesen.k"},
        {"name" : "Ian Langmore",               "user" : "langmore.i"},
        {"name" : "Chris Lasher",               "user" : "lasher.c"},
        {"name" : "Doug Latornell",             "user" : "latornell.d"},
        {"name" : "Stephen McGough",            "user" : "mcgough.s"},
        {"name" : "Jessica McKellar",           "user" : "mckellar.j"},
        {"name" : "Emily Jane McTavish",        "user" : "mctavish.ej"},
        {"name" : "Ian Mitchell",               "user" : "mitchell.i"},
        {"name" : "Lex Nederbragt",             "user" : "nederbragt.l"},
        {"name" : "Aleksandra Pawlik",          "user" : "pawlik.a"},
        {"name" : "Jason Pell",                 "user" : "pell.j"},
        {"name" : "Fernando Perez",             "user" : "perez.f"},
        {"name" : "Caitlyn Pickens",            "user" : "pickens.c"},
        {"name" : "Ariel Rokem",                "user" : "rokem.a"},
        {"name" : "Anthony Scopatz",            "user" : "scopatz.a"},
        {"name" : "Jeff Shelton",               "user" : "shelton.j"},
        {"name" : "Joshua Ryan Smith",          "user" : "smith.j"},
        {"name" : "Sarah Supp",                 "user" : "supp.s"},
        {"name" : "Tracy Teal",                 "user" : "teal.t"},
        {"name" : "Nelle Varoquaux",            "user" : "varoquaux.n"},
        {"name" : "Alex Viana",                 "user" : "viana.a"},
        {"name" : "Ben Waugh",                  "user" : "waugh.b"},
        {"name" : "Ethan White",                "user" : "white.e"},
        {"name" : "Lynne Williams",             "user" : "williams.l"},
        {"name" : "Greg Wilson",                "user" : "wilson.g"}
    ],
    "organizer" : [
        {"name" : "Jorge Aranda",               "user" : "aranda.j"},
        {"name" : "Casey Bergman",              "user" : "bergman.c"},
        {"name" : "Bruce Berriman",             "user" : "berriman.b"},
        {"name" : "Onno Broekmans",             "user" : "broekmans.o"},
        {"name" : "Amy Brown",                  "user" : "brown.amy"},
        {"name" : "Shreyas Cholia",             "user" : "cholia.s"},
        {"name" : "Stefano Cozzini",            "user" : "cozzini.s"},
        {"name" : "Ross Dickson",               "user" : "dickson.r"},
        {"name" : "Dan Ellis",                  "user" : "ellis.dan"},
        {"name" : "Philip Fowler",              "user" : "fowler.p"},
        {"name" : "Carole Goble",               "user" : "goble.c"},
        {"name" : "Chris Gray",                 "user" : "gray.c"},
        {"name" : "James Hetherington",         "user" : "hetherington.james"},
        {"name" : "Bill Howe",                  "user" : "howe.b"},
        {"name" : "Damien Irving",              "user" : "irving.d"},
        {"name" : "Nic Kooyers",                "user" : "kooyers.n"},
        {"name" : "Ian Langmore",               "user" : "langmore.i"},
        {"name" : "Paul Lu",                    "user" : "lu.p"},
        {"name" : "Andrew Lumsdaine",           "user" : "lumsdaine.a"},
        {"name" : "Joshua Madin",               "user" : "madin.j"},
        {"name" : "Damian Marchewka",           "user" : "marchewka.damian"},
        {"name" : "Ian M. Mitchell",            "user" : "mitchell.i"},
        {"name" : "Jason Montojo",              "user" : "montojo.j"},
        {"name" : "Lex Nederbragt",             "user" : "nederbragt.l"},
        {"name" : "Chris Paciorek",             "user" : "paciorek.c"},
        {"name" : "Marian Petre",               "user" : "petre.m"},
        {"name" : "Jon Pipitone",               "user" : "pipitone.j"},
        {"name" : "Mark Plumbley",              "user" : "plumbley.m"},
        {"name" : "Michael Rezny",              "user" : "rezny.m"},
        {"name" : "Rachel Schutt",              "user" : "schutt.r"},
        {"name" : "Jeff Shelton",               "user" : "shelton.j"},
        {"name" : "Andrew Su",                  "user" : "su.a"},
        {"name" : "Todd Vision",                "user" : "vision.t"},
        {"name" : "Ben Waugh",                  "user" : "waugh.b"},
        {"name" : "Ethan White",                "user" : "white.e"},
        {"name" : "Greg Wilson",                "user" : "wilson.g"},
        {"name" : "Robin Wilson",               "user" : "wilson.r"},
        {"name" : "Paul Wilson",                "user" : "wilson.p"},
        {"name" : "David Wolever",              "user" : "wolever.d"}
    ]
}
category : {
    "assessment" : "Assessment",
    "boot-camp" : "Boot Camp",
    "community" : "Community",
    "content" : "Content",
    "education" : "Education",
    "evaluation" : "Evaluation",
    "interviews" : "Interviews",
    "jobs" : "Jobs",
    "lectures" : "Lectures",
    "licensing" : "Licensing",
    "minutes" : "Meeting Minutes",
    "noticed" : "Noticed",
    "opinion" : "Opinion",
    "research" : "Research",
    "sponsors" : "Sponsors",
    "sponsors/cybera" : "Cybera",
    "sponsors/enthought" : "Enthought",
    "sponsors/indiana-university" : "Indiana University",
    "sponsors/mathworks" : "MathWorks",
    "sponsors/michigan-state-university" : "Michigan State University",
    "sponsors/microsoft" : "Microsoft",
    "sponsors/mitacs" : "MITACS",
    "sponsors/mozilla" : "Mozilla",
    "sponsors/python-software-foundation" : "Python Software Foundation",
    "sponsors/queen-mary-university-of-london" : "Queen Mary University of London",
    "sponsors/scimatic" : "Scimatic",
    "sponsors/scinet" : "SciNet",
    "sponsors/sharcnet" : "SHARCNET",
    "sponsors/sloan-foundation" : "Sloan Foundation",
    "sponsors/sound-software" : "SoundSoftware",
    "sponsors/uk-met-office" : "UK Met Office",
    "stories" : "Success Stories",
    "tooling" : "Tooling",
    "tutorial" : "Tutorial",
    "uncategorized" : "Uncategorized",
    "venues" : "Venues",
    "venues/american-university-beirut" : "American University of Beirut",
    "venues/bernstein-berlin" : "Bernstein Center - Berlin",
    "venues/boston" : "Boston",
    "venues/caltech" : "Caltech",
    "venues/cef-2011" : "CEF 2011",
    "venues/columbia-university" : "Columbia University",
    "venues/duke-university" : "Duke University",
    "venues/ebi-cambridge" : "EBI Cambridge",
    "venues/edinburgh" : "University of Edinburgh",
    "venues/egi-forum" : "EGI Forum",
    "venues/eresearch-nz" : "eResearch New Zealand",
    "venues/halifax" : "Halifax",
    "venues/ictp" : "International Center for Theoretical Physics",
    "venues/indiana-university" : "Indiana University",
    "venues/inria-paris" : "INRIA Paris",
    "venues/international-center-for-theoretical-physics" : "International Center for Theoretical Physics",
    "venues/johns-hopkins-university" : "Johns Hopkins University",
    "venues/ju-krakow" : "Jagiellonian University Krakow",
    "venues/kaust" : "King Abdullah University of Science and Technology",
    "venues/learnhub" : "LearnHub",
    "venues/lawrence-berkeley-lab" : "Lawrence Berkeley Laboratory",
    "venues/llnl" : "Lawrence Livermore National Laboratory",
    "venues/mannheim" : "Universitaet Mannheim",
    "venues/macquarie-university" : "Macquarie Universty",
    "venues/max-planck-institute-tuebingen" : "Max Planck Institute, Tuebingen",
    "venues/mcgill" : "McGill University",
    "venues/melbourne" : "University of Melbourne",
    "venues/michigan-state" : "Michigan State University",
    "venues/monterey-bay-aquarium-research-institute" : "Monterey Bay Aquarium Research Institute",
    "venues/mozilla" : "Mozilla",
    "venues/ncar" : "National Center for Atmospheric Research",
    "venues/nersc" : "NERSC",
    "venues/nescent" : "NESCENT",
    "venues/online" : "Online",
    "venues/oxford" : "Oxford University",
    "venues/purdue-university" : "Purdue University",
    "venues/qmul" : "Queen Mary University of London",
    "venues/rutherford-appleton-laboratory" : "Rutherford Appleton Laboratory",
    "venues/saint-marys-university" : "Saint Mary's University",
    "venues/salk-institute" : "Salk Institute",
    "venues/scripps-institute" : "Scripps Institute",
    "venues/stanford" : "Stanford University",
    "venues/stellenbosch-university" : "Stellenbosch University",
    "venues/stsci" : "Space Telescope Science Institute",
    "venues/uc-berkeley" : "University of California - Berkeley",
    "venues/uc-davis" : "University of California - Davis",
    "venues/uc-san-diego" : "University of California - San Diego",
    "venues/uc-san-francisco" : "University of California - San Francisco",
    "venues/ukmo" : "UK Met Office",
    "venues/umass-amherst" : "University of Massachusetts Amherst",
    "venues/university-college-london" : "University College London",
    "venues/university-of-alberta" : "University of Alberta",
    "venues/university-of-arizona" : "University of Arizona",
    "venues/university-of-british-columba" : "University of British Columba",
    "venues/university-of-chicago" : "University of Chicago",
    "venues/university-of-glasgow" : "University of Glasgow",
    "venues/university-of-manchester" : "University of Manchester",
    "venues/university-of-oslo" : "University of Oslo",
    "venues/university-of-southampton" : "University of Southampton",
    "venues/university-of-toronto" : "University of Toronto",
    "venues/university-of-virginia" : "University of Virginia",
    "venues/university-of-washington" : "University of Washington",
    "venues/university-of-wisconsin" : "University of Wisconsin - Madison",
    "venues/utah-state-university" : "Utah State University",
    "venues/vrije-universiteit" : "Vrije Universiteit Amsterdam",
    "venues/wise" : "Women in Science and Engineering",
    "versions/version-2" : "Version 2",
    "versions/version-3" : "Version 3",
    "versions/version-4" : "Version 4",
    "versions/version-4-1" : "Version 4.1",
    "versions/version-5-0" : "Version 5.0",
    "versions/version-5-1" : "Version 5.1"
}
people : {
    "ahmadia.a" : "Aron Ahmadia",
    "anderson.c" : "Carlos Anderson",
    "antonioletti.m" : "Mario Antonioletti",
    "aruliah.d" : "Dhavide Aruliah",
    "bernabeu.m" : "Miguel Bernabeu",
    "blanco-cuaresma.s" : "Sergi Blanco Cuaresma",
    "blischak.j" : "John Blischak",
    "bostroem.a" : "Azalee Bostroem",
    "bray.e" : "Erik Bray",
    "broekmans.o" : "Onno Broekmans",
    "brown.amy" : "Amy Brown",
    "brown.ct" : "C. Titus Brown",
    "bryan.j" : "Jennifer Bryan",
    "buske.o" : "Orion Buske",
    "cabral.sheeri" : "Sheeri Cabral",
    "cannam.c" : "Chris Cannam",
    "chapman.h" : "Hanah Chapman",
    "chuang-howe.a" : "Adina Chuang Howe",
    "chue-hong.n" : "Neil Chue Hong",
    "cooper.j" : "Jonathan Cooper",
    "cossou.c" : "Christophe Cossou",
    "cozzini.s" : "Stefano Cozzini",
    "cranston.k" : "Karen Cranston",
    "davenport.e" : "Emily Davenport",
    "davis.m" : "Matt Davis",
    "dickson.r" : "Ross Dickson",
    "ely.j" : "Justin Ely",
    "elza.dethe" : "Dethe Elza",
    "enbody.r" : "Richard Enbody",
    "figueira.l" : "Luis Figueira",
    "foertter.f" : "Fernanda Foertter",
    "gidden.matt" : "Matt Gidden",
    "gramfort.a" : "Alexandre Gramfort",
    "gustavsen.j" : "Julia Gustavsen",
    "guy.t" : "Tommy Guy",
    "hansen.m" : "Michael Hansen",
    "hart.t" : "Ted Hart",
    "hauser.e" : "Elliot Hauser",
    "hetherington.j" : "James Hetherington",
    "hettrick.s" : "Simon Hettrick",
    "hinsen.k" : "Konrad Hinsen",
    "huff.k" : "Katy Huff",
    "ivanov.p" : "Paul Ivanov",
    "jackson.m" : "Mike Jackson",
    "jones.d" : "David Jones",
    "kerr.j" : "Jessica Kerr",
    "ketcheson.david" : "David Ketcheson",
    "kitzes.j" : "Justin Kitzes",
    "konrad.b" : "Bernhard Konrad",
    "koop.d" : "David Koop",
    "lagesen.k" : "Karin Lagesen",
    "lawson.a" : "Ainsley Lawson",
    "lewis.chloe" : "Chloe Lewis",
    "limare.n" : "Nicolas Limare",
    "mandli.kyle" : "Kyle Mandli",
    "mcglinn.d" : "Dan McGlinn",
    "mcgough.s" : "Steve McGough",
    "mckellar.j" : "Jessica McKellar",
    "mctavish.ej" : "Emily Jane McTavish",
    "merrelli.aronne" : "Aronne Merrelli",
    "morris.b" : "Ben Morris",
    "morrison.j" : "James Morrison",
    "nederbragt.l" : "Lex Nederbragt",
    "nielsen.c" : "Charlene Nielsen",
    "olson.r" : "Randy Olson",
    "pawlik.a" : "Aleksandra Pawlik",
    "pennekamp.f" : "Frank Pennekamp",
    "peterson.j" : "Joshua L. Peterson",
    "pickens.c" : "Caitlyn Pickens",
    "pipitone.j" : "Jon Pipitone",
    "punch.bill" : "Bill Punch",
    "ram.k" : "Karthik Ram",
    "rokem.a" : "Ariel Rokem",
    "scopatz.a" : "Anthony Scopatz",
    "selik.m" : "Michael Selik",
    "shelton.j" : "Jeffrey Shelton",
    "smith.a" : "Andrew Smith",
    "smith.j" : "Josh Smith",
    "sufi.s" : "Shoaib Sufi",
    "supp.s" : "Sarah Supp",
    "teal.t" : "Tracy Teal",
    "terrel.a" : "Andy Terrel",
    "trimble.will" : "Will Trimble",
    "viana.a" : "Alex Viana",
    "vanderplas.jacob" : "Jake VanderPlas",
    "varoquaux.n" : "Nelle Varoquaux",
    "varoquaux.g" : "Gael Varoquaux",
    "waugh.b" : "Ben Waugh",
    "white.e" : "Ethan White",
    "williams.l" : "Lynne Williams",
    "wilson.g" : "Greg Wilson",
    "wilson.p" : "Paul Wilson",
    "wilson.r" : "Robin Wilson",
    "woods.c" : "Christopher Woods",
    "yu.terri" : "Terri Yu",
    "yunis.enas" : "Enas Yunis",
    "zarrabeitia.l" : "Luis Zarrabeitia"
}
