- https://github.com/swcarpentry/2013-08-23-harvard
- https://github.com/swcarpentry/2013-09-16-stsci
- https://github.com/jdblischak/2013-09-19-chicago
- https://github.com/arokem/2013-09-16-ISI
- https://github.com/swcarpentry/2013-10-09-canberra
- https://github.com/swcarpentry/2013-10-24-greenwich
- https://github.com/amyrbrown/2014-01-06-plantbreeding
