- https://github.com/swcarpentry/2013-08-23-harvard
- https://github.com/swcarpentry/2013-09-16-stsci
- https://github.com/jdblischak/2013-09-19-chicago
- https://github.com/arokem/2013-09-16-ISI
- https://github.com/jdblischak/2013-10-03-pasteur
- https://github.com/swcarpentry/2013-10-09-canberra
- https://github.com/jdblischak/2013-10-17-uic
- https://github.com/swcarpentry/2013-10-24-greenwich
- https://github.com/justincely/2013-10-25-columbia
- https://github.com/chryswoods/2013-11-14-exeter
- https://github.com/mikej888/2013-12-03-edinburgh
- https://github.com/adina/2014-01-08-iastate
- https://github.com/arokem/2014-01-27-Stanford
- https://github.com/damienirving/2013-11-25-unimelb
- https://github.com/rhiever/2014-01-30-mit
- https://github.com/damienirving/2014-02-10-hobart
- https://github.com/swcarpentry/2014-02-11-toronto
