- https://github.com/swcarpentry/2013-08-23-harvard
- https://github.com/swcarpentry/2013-09-16-stsci
- https://github.com/jdblischak/2013-09-19-chicago
- https://github.com/arokem/2013-09-16-ISI
- https://github.com/jdblischak/2013-10-03-pasteur
- https://github.com/swcarpentry/2013-10-09-canberra
- https://github.com/jdblischak/2013-10-17-uic
- https://github.com/swcarpentry/2013-10-24-greenwich
- https://github.com/justincely/2013-10-25-columbia
- https://github.com/mikej888/2013-12-03-edinburgh
- https://github.com/amyrbrown/2014-01-06-plantbreeding
- https://github.com/adina/2014-01-08-iastate
- https://github.com/arokem/2014-01-27-Stanford
