board_inquiries : "board-inquiries@software-carpentry.org"
contact         : "admin@software-carpentry.org"
facebook_url    : "https://www.facebook.com/SoftwareCarpentry"
github_url      : "https://github.com/swcarpentry"
github_io_url   : "http://swcarpentry.github.io"
google_plus_url : "https://plus.google.com/+Software-carpentryOrg"
paypal_url      : "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MYSDWRR8HWFR6"
rss_url         : "http://software-carpentry.org/feed.xml"
site_url        : "http://software-carpentry.org"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
msl_url         : "http://mozillascience.org"
store_url       : "http://www.cafepress.com/swcarpentry"
recent_length   : 6
upcoming_length : 10
blog_title      : "Software Carpentry"
blog_subtitle   : "Helping scientists make better software since 1998"
training_url    : "http://teaching.software-carpentry.org"
mailing_lists   : "http://lists.software-carpentry.org"
flag_size       : 16
exclude         : [standard_config.yml, badges_config.yml, bootcamp_cache.yml, talks]
