- https://github.com/camillescott/2015-08-16-ucdavis-wise
- https://github.com/statkclee/2015-08-20-daejeon
- https://github.com/vu-bc/2015-08-20-vanderbilt
- https://github.com/eddelbuettel/2015-08-21-nw
- https://github.com/resbaz/2015-08-24-matlab
- https://github.com/datacarpentry/2015-08-24-Sloan-Kettering
- https://github.com/dgasmith/2015-08-24-stanford
- https://github.com/sungeunbae/2015-08-24-vuw
- https://github.com/andreww/2015-08-26-leeds
- https://github.com/umswc/2015-08-26-umswc
- https://github.com/uw-madison-aci/2015-08-26-uw-madison
- https://github.com/anelda/2015-09-06-saeon
- https://github.com/dpshelio/2015-09-07-guildford
- https://github.com/callaghanmt/2015-09-10-leeds
- https://github.com/rgaiacs/2015-09-10-usp
- https://github.com/jdblischak/2015-09-15-chicago
- https://github.com/emilydolson/2015-09-15-msu
- https://github.com/Southampton-RSG/2015-09-17-southampton
- https://github.com/bio-swc-bne/2015-09-28-UQ
- https://github.com/jcu-eresearch/2015-10-01-JamesCookUni
- https://github.com/luispedro/2015-11-04-embl
- https://github.com/ocefpaf/2015-08-31-UFBA
- https://github.com/UMSWC/2015-10-19-UMich
