- https://github.com/weecology/2015-03-16-utahstate
- https://github.com/rmdickson/2015-03-18-stfx
- https://github.com/jlant/2015-03-19-arkansas
- https://github.com/amjoconn/2015-03-21-uwaterloo
- https://github.com/iglpdc/2015-03-23-hsph
- https://github.com/oulibraries/2015-03-24-ou
- https://github.com/COMBINE-Australia/2015-04-08-SWC-UniMelb-Biosciences
- https://github.com/efran/2015-04-09-UW
- https://github.com/hpcarcher/2015-04-16-imperial
- https://github.com/jdblischak/2015-04-17-nw
- https://github.com/mqwilber/2015-04-17-ucsb
- https://github.com/naupaka/2015-04-18-UT-Arlington
- https://github.com/xuf12/2015-04-02-umiami
- https://github.com/karawoo/2015-04-27-wsu
- https://github.com/ttimbers/2015-04-30-SFU
- https://github.com/pbarmby/2015-05-11-westernu
- https://github.com/resbaz/2015-05-25-unimelb
- https://github.com/bio-swc-bne/2015-07-02-UQ
- https://github.com/damienirving/2015-07-13-amos
