- https://github.com/arohl/2015-07-20-perth
- https://github.com/fasrc/2015-07-22_SWC-R
# - https://github.com/usnistgov/2015-07-23-nist
- https://github.com/i5k-kinbre-script-share/2015-07-23-stanford
- https://github.com/billmills/2015-07-24-LSIUBC
- https://github.com/dipnet/2015-08-03-IBRC-Indonesia
- https://github.com/dotsdl/2015-08-04-asu_sese
- https://github.com/intersectaustralia/2015-08-05-UWS
- https://github.com/mperignon/2015-08-06-cuboulder
- https://github.com/mestato/2015-08-10-UTKnoxville
- https://github.com/camillescott/2015-08-16-ucdavis-wise
- https://github.com/eddelbuettel/2015-08-21-nw
- https://github.com/vu-bc/2015-08-20-vanderbilt
- https://github.com/resbaz/2015-08-24-matlab
- https://github.com/datacarpentry/2015-08-24-Sloan-Kettering
- https://github.com/dgasmith/2015-08-24-stanford
- https://github.com/sungeunbae/2015-08-24-vuw
- https://github.com/andreww/2015-08-26-leeds
- https://github.com/umswc/2015-08-26-umswc
- https://github.com/callaghanmt/2015-09-10-leeds
- https://github.com/bio-swc-bne/2015-09-28-UQ
- https://github.com/jcu-eresearch/2015-10-01-JamesCookUni
- https://github.com/luispedro/2015-11-04-embl
